export type DefaultFeaturePlugin = {
  key: string;
  name: string;
  description: string;
  category: string;
  version: string;
  installed: boolean;
  enabled: boolean;
  editable: boolean;
  isCore: boolean;
  routePath?: string | null;
  areas: string[];
  sortOrder: number;
  config?: Record<string, unknown>;
};

export const DEFAULT_FEATURE_PLUGINS: DefaultFeaturePlugin[] = [
  {
    key: 'plugin_center',
    name: 'Plugin Center',
    description: 'Registry and configuration editor for all installable product capabilities.',
    category: 'platform',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: false,
    isCore: true,
    routePath: '/admin/plugins',
    areas: ['admin'],
    sortOrder: 1,
    config: {
      routes: ['/admin/plugins'],
      lockFlags: ['installed', 'enabled'],
    },
  },
  {
    key: 'admin_dashboard',
    name: 'Admin Dashboard',
    description: 'Portfolio KPI cockpit for operations leaders and supervisors.',
    category: 'admin',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: true,
    routePath: '/admin',
    areas: ['admin'],
    sortOrder: 10,
    config: { routes: ['/admin'] },
  },
  {
    key: 'ai_assistant',
    name: 'ChatGPT Assistant',
    description: 'Admin-only AI workspace for drafting content, support replies and operations summaries.',
    category: 'platform',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/ai',
    areas: ['admin'],
    sortOrder: 15,
    config: {
      routes: ['/admin/ai'],
      apiPrefixes: ['/ai'],
      provider: 'openai',
    },
  },
  {
    key: 'website_settings',
    name: 'Website Settings',
    description: 'Centralized public website settings for logo, hotline, footer, FAQ, pricing and CTA content.',
    category: 'public',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/website-settings',
    areas: ['admin', 'public'],
    sortOrder: 17,
    config: {
      routes: ['/admin/website-settings'],
      apiPrefixes: ['/website-settings'],
    },
  },
  {
    key: 'media_library',
    name: 'Media Library',
    description: 'Upload, classify and reuse images across website, CMS and product surfaces.',
    category: 'platform',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/media',
    areas: ['admin'],
    sortOrder: 18,
    config: {
      routes: ['/admin/media'],
      apiPrefixes: ['/media'],
    },
  },
  {
    key: 'customer_dashboard',
    name: 'Customer Dashboard',
    description: 'High-level customer portal experience with energy and savings overview.',
    category: 'customer',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: true,
    routePath: '/customer',
    areas: ['customer'],
    sortOrder: 20,
    config: { routes: ['/customer'] },
  },
  {
    key: 'customers',
    name: 'Customers',
    description: 'Customer account creation, segmentation and profile management.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/customers',
    areas: ['admin'],
    sortOrder: 30,
    config: {
      routes: ['/admin/customers'],
      apiPrefixes: ['/customers'],
    },
  },
  {
    key: 'users',
    name: 'Users & Roles',
    description: 'Internal user management, role assignment and access delegation for operations teams.',
    category: 'platform',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/users',
    areas: ['admin'],
    sortOrder: 35,
    config: {
      routes: ['/admin/users'],
      apiPrefixes: ['/users', '/roles'],
    },
  },
  {
    key: 'systems',
    name: 'Systems',
    description: 'Solar asset inventory, site performance and inverter metadata.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/systems',
    areas: ['admin', 'customer'],
    sortOrder: 40,
    config: {
      routes: ['/admin/systems', '/customer/systems'],
      apiPrefixes: ['/systems'],
    },
  },
  {
    key: 'operational_data',
    name: 'Operational Data',
    description: 'Manual-first monthly operating data, CSV import and semi-automatic portfolio updates.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/operations-data',
    areas: ['admin'],
    sortOrder: 42,
    config: {
      routes: ['/admin/operations-data'],
      apiPrefixes: ['/operational-data'],
    },
  },
  {
    key: 'solarman_connections',
    name: 'SOLARMAN',
    description: 'Customer-account integration for SOLARMAN station discovery, monthly PV sync and billing ingestion.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/solarman',
    areas: ['admin'],
    sortOrder: 45,
    config: {
      routes: ['/admin/solarman'],
      apiPrefixes: ['/solarman-connections'],
    },
  },
  {
    key: 'deye_connections',
    name: 'Deye OpenAPI',
    description: 'Official DeyeCloud OpenAPI integration for token auth, station sync, device sync and monthly PV billing ingestion.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/deye',
    areas: ['admin'],
    sortOrder: 46,
    config: {
      routes: ['/admin/deye'],
      apiPrefixes: ['/deye-connections'],
    },
  },
  {
    key: 'contracts',
    name: 'Contracts',
    description: 'Commercial contract lifecycle, attached files and pricing terms.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/contracts',
    areas: ['admin', 'customer'],
    sortOrder: 50,
    config: {
      routes: ['/admin/contracts', '/customer/contracts'],
      apiPrefixes: ['/contracts'],
    },
  },
  {
    key: 'energy_records',
    name: 'Energy Records',
    description: 'Daily production, consumption, grid import and inverter sync records.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/systems',
    areas: ['admin'],
    sortOrder: 60,
    config: {
      apiPrefixes: ['/energy-records'],
    },
  },
  {
    key: 'billing',
    name: 'Billing',
    description: 'Invoice generation, PDF export and billing operations across contract models.',
    category: 'finance',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/billing',
    areas: ['admin', 'customer'],
    sortOrder: 70,
    config: {
      routes: ['/admin/billing', '/admin/zalo', '/customer/billing'],
      apiPrefixes: ['/invoices', '/zalo-notifications'],
    },
  },
  {
    key: 'payments',
    name: 'Payments',
    description: 'Online gateway flows, reconciliation and payment history.',
    category: 'finance',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/customer/payments',
    areas: ['admin', 'customer'],
    sortOrder: 80,
    config: {
      routes: ['/customer/payments'],
      apiPrefixes: ['/payments'],
    },
  },
  {
    key: 'support',
    name: 'Support',
    description: 'Ticket intake, SLA handling and issue response workflows.',
    category: 'operations',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/support',
    areas: ['admin', 'customer'],
    sortOrder: 90,
    config: {
      routes: ['/admin/support', '/customer/support'],
      apiPrefixes: ['/support-tickets'],
    },
  },
  {
    key: 'reports',
    name: 'Reports',
    description: 'Revenue, energy and collection analytics for management reporting.',
    category: 'analytics',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/reports',
    areas: ['admin'],
    sortOrder: 100,
    config: {
      routes: ['/admin/reports'],
      apiPrefixes: ['/reports'],
    },
  },
  {
    key: 'service_packages',
    name: 'Service Packages',
    description: 'Commercial product packaging, VAT rules and pricing strategy editor.',
    category: 'product',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/packages',
    areas: ['admin'],
    sortOrder: 110,
    config: {
      routes: ['/admin/packages'],
      apiPrefixes: ['/service-packages'],
    },
  },
  {
    key: 'notifications',
    name: 'Notifications',
    description: 'In-app alerts, billing reminders and operational announcements.',
    category: 'engagement',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/customer',
    areas: ['admin', 'customer'],
    sortOrder: 120,
    config: {
      apiPrefixes: ['/notifications'],
    },
  },
  {
    key: 'customer_profile',
    name: 'Customer Profile',
    description: 'Profile, site address and account-level preferences in the customer portal.',
    category: 'customer',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/customer/profile',
    areas: ['customer'],
    sortOrder: 130,
    config: {
      routes: ['/customer/profile'],
      apiPrefixes: ['/customers/me/profile'],
    },
  },
  {
    key: 'marketing_pages',
    name: 'Marketing Pages',
    description: 'Public-facing landing pages plus admin CMS for homepage, about, solutions, contact and pricing.',
    category: 'public',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/',
    areas: ['public', 'admin'],
    sortOrder: 140,
    config: {
      routes: ['/', '/about', '/solutions', '/pricing', '/contact', '/admin/cms'],
      apiPrefixes: ['/marketing-pages'],
    },
  },
  {
    key: 'contact_inquiries',
    name: 'Contact Inquiries',
    description: 'Public consultation form and admin lead handling workflow.',
    category: 'public',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/leads',
    areas: ['public', 'admin'],
    sortOrder: 143,
    config: {
      routes: ['/contact', '/admin/leads'],
      apiPrefixes: ['/contact-inquiries'],
    },
  },
  {
    key: 'website_ai_chat',
    name: 'Website AI Chat',
    description: 'Floating website assistant with guarded public chat for pricing, FAQs and conversion support.',
    category: 'public',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/',
    areas: ['public', 'admin'],
    sortOrder: 144,
    config: {
      routes: ['/'],
      apiPrefixes: ['/ai/public-chat'],
    },
  },
  {
    key: 'content_posts',
    name: 'Content Posts',
    description: 'Staff-managed articles, case studies and public news pages.',
    category: 'public',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/admin/posts',
    areas: ['admin', 'public'],
    sortOrder: 145,
    config: {
      routes: ['/news', '/news/[slug]', '/admin/posts'],
      apiPrefixes: ['/content-posts'],
    },
  },
  {
    key: 'localization',
    name: 'Localization',
    description: 'Multi-language experience and language switcher controls.',
    category: 'platform',
    version: '1.0.0',
    installed: true,
    enabled: true,
    editable: true,
    isCore: false,
    routePath: '/',
    areas: ['public', 'admin', 'customer'],
    sortOrder: 150,
    config: {
      locales: ['vi', 'en'],
    },
  },
];

export function buildDefaultFeaturePlugins(): DefaultFeaturePlugin[] {
  return DEFAULT_FEATURE_PLUGINS.map((plugin) => ({
    ...plugin,
    areas: [...plugin.areas],
    config: plugin.config ? JSON.parse(JSON.stringify(plugin.config)) : undefined,
  }));
}
